# This file was generated by GoReleaser. DO NOT EDIT.
cask "ms365-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "9f4a88860ef4b77b3abbc973fc70f57e5dbec2e7af5d1dc260aaec175425fba4"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "782f1e2e345fe17a8a42bc0a0d2bc97da3c8208f0966e9bc3be64955eefb1af3"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6d33ce9c9fcee696699ef9b9ae224d0d454a2cfa40b7d9243ed3c09159ad940"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "458e08e29abd7f65ecfc565c2c88b1f22f143436f3b2b8978021c3df7d711fbb"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ms365-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/ms365-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ms365"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ms365"]
  end

  # No zap stanza required

end
