# This file was generated by GoReleaser. DO NOT EDIT.
cask "ms365-cli" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "fae8003fcb963d9b74441d1a7d01b765081b44c948679d6f8f4d44186d86faf3"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea341eee85a90b5a04732103a71dab8c267020db53a3ac9eb3484548e9fbe902"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4a7d94e4bc6ef6406606aa3f31968b11dce7bb5d1a4ed2daed44153e9dc78523"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9a9dd48b55c16a220593bef550f7f2f260952e1e73e474e7edd3bdd34a8915b"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ms365-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/ms365-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ms365"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ms365"]
  end

  # No zap stanza required
end
