# This file was generated by GoReleaser. DO NOT EDIT.
cask "ms365-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cf7b262cea1a22005e34132465c1c6d0fb2ab0ed8701a14091a8ee64367a9bee"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40c25b65b023c3f482b982d018547db294041ab3c55ee1eec520a1ae73c8ad76"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9892aa3420ac8dc8e4f1578967decf4fa34ad0dda79758a13c8c75ab6eb7dc1a"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66b9fa9a3301076ca5ce200f1d4cdb7b177e1aa0da9841eb41507acb27ed9520"
      url "https://github.com/jjuanrivvera/ms365-cli/releases/download/v#{version}/ms365-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ms365-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/ms365-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ms365"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ms365"]
  end

  # No zap stanza required

end
